AllCops:
  NewCops: enable

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 198

RSpec/MultipleExpectations:
  Enabled: false
